name: Cypress Tests with Dependency and Artifact Caching

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cypress Install Dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Save Build Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: dist

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 60
          browser: chrome
          record: false
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}

      # Save Cypress videos and screenshots for analysis
      - name: Upload Cypress Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports

      # (Optional) Save JUnit/HTML Reports
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: cypress/results/
